## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Stefanie & Noah"
theme = "hugo-story"
baseURL= "https://stefanieundnoah.ch"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = ""
  logo = "images/schwarsee2m.png"
  favicon = true

[Params.social]
  email = "hallo@stefanieundnoah.ch"
