name = "Hugo Story"
description = "A (modular, highly tweakable) responsive one-page theme for Hugo."
homepage = "https://caressofsteel.github.io/demos/hugo/hugo-story/"

min_version = "0.67.3 Extended"
tags = ["blog","clean","html5up","modular","one-page","portfolio","responsive"]
features = ["font-awesome","favicon","one-page","responsive","sass","scss"]

license = "Creative Commons"
licenselink = "https://github.com/caressofsteel/hugo-story/blob/master/LICENSE"

[author]
    name = "caressofsteel"
    homepage = "https://github.com/caressofsteel"
    repo = "https://github.com/caressofsteel/hugo-story"

# If porting an existing theme
[original]
    author = "HTML5UP"
    homepage = "https://html5up.net"
    repo = "https://html5up.net/story"